name = "zerodev-kernel-ecdsa-signer"
version = "0.0.1"
description = "Kernel ERC-4337 infrastructure"

[deploy.ECDSASigner]
artifact = "ECDSASigner"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"
