[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "paris"
auto_detect_remappings = false
via_ir = true
cbor_metadata = false
use_literal_content = false
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200
