[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "paris"
via_ir = true
cbor_metadata = true
use_literal_content = false
bytecode_hash = "ipfs"
optimizer = true
optimizer_runs = 10000000
libraries = []
allow_paths = ["../../../internal"]
fs_permissions = [
    { access = "read-write", path = "deployments" },
    { access = "read", path = "../../../eth-infinitism/entrypoint/0.7/deployments" },
    { access = "read", path = "data" },
    { access = "read", path = "out" },
]
