[profile.default]
src = "node_modules"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
auto_detect_solc = false
solc_version = "0.8.25"
evm_version = "paris"
via_ir = false
cbor_metadata = true
use_literal_content = false
bytecode_hash = "ipfs"
optimizer = true
optimizer_runs = 200
libraries = []
