name = "zerodev-kernel-call-policy"
version = "0.0.4"
description = "Kernel ERC-4337 infrastructure"

[deploy.CallPolicy]
artifact = "CallPolicy"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"
