[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
evm_version = "paris"
cbor_metadata = true
use_literal_content = true
bytecode_hash = "ipfs"
optimizer = true
optimizer_runs = 1000000
libraries = []
