name = "zerodev-kernel-signature-policy"
version = "0.0.1"
description = "Kernel ERC-4337 infrastructure"

[deploy.SignaturePolicy]
artifact = "SignaturePolicy"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"
