name = "zerodev-kernel-web-authn-signer"
version = "0.0.2"
description = "Kernel ERC-4337 infrastructure"

[pull.p256Verifier]
source = "daimo-p256-verifier:1.0.0"

[deploy.WebAuthnSigner]
artifact = "WebAuthnSigner"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"
