name = "eth-infinitism-entrypoint"
version = "0.7.0"
description = "ERC-4337 infrastructure"

[deploy.EntryPoint]
artifact = "EntryPoint"
create2 = true
salt = "0x90d8084deab30c2a37c45e8d47f49f2f7965183cb6990a98943ef94940681de3"
ifExists = "continue"
