name: verify
on:
  push:
    branches: [main]
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cannon
        run: npm install -g @usecannon/cli

      - name: Install foundryup
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          echo "$HOME/.config/.foundry/bin" >> "$GITHUB_PATH"

      - name: Install foundry
        run: make install-foundry

      - run: make
